### ISSUE TITLE
Self-hosting radix gateway exploration

### ISSUE THREAD

**Issue by amirmrad** [mlabs-haskell/radix-snapshot-poll-concept#2]
Current snapshot polling relies heavily on a performant gateway in order to query voters accounts and compute vote tallies. It is therefore ideal to be able to locally test, and if required, self-host a dedicated instance of the Radix gateway for snapshot polling. To do so we first need to explore how to run the gateway locally in a development environment.

### Objectives
- Identify dependencies and requirements
- Run a local instance of [babylon-node](https://github.com/radixdlt/babylon-node) connected to the latest Radix testnet (RCNetV3)
- Run a local instance of [babylon-gateway](https://github.com/radixdlt/babylon-gateway) connected core node
- Provide a guide to running the setup locally in a development environment

### Further Objectives
- Identify hardware/software requirements for future self-hosting
- Explore querying the underlying postgres database as an alternative to querying via the provided Gateway endpoints

**Comment by mikekeke** [comment]
# Current approach

The current approach is to use a bit customized setup of Network Gateway.

Official out-of-the box setup for dApp can be found on [this image](https://docs.radixdlt.com/main/node-and-gateway/_images/network-gateway-deployment.png) in [documentation](https://docs.radixdlt.com/main/node-and-gateway/network-gateway-setup.html). Parts that required for snapshot polling prototype are `Full Node`, `Data Aggregator` and `Postgres DB`. To query data from the database we decided to use own simple service instead of Gateway. The reasons are:
- Gateway API method, which can be used to query historical balance for the account, has limit on amount of addresses (about 10) that can be queried in a single request. Also it queries and returns a lot of data (first from database and then over the wire), that are not required to make snapshot polling to work
- Depending on how snapshot polling will be integrated into frontend, we can provide TS/JS SDK instead of REST API backend, to remove one layer of IO for better throughput

Hardware and software requirements are derived from [official requirements of Network Gateway](https://docs.radixdlt.com/main/node-and-gateway/network-gateway-setup-custom-requirements.html). TLDR for production environment:
- `Node`: c5.2xlarge or equivalent, vCPU - 8, RAM - 16 GB, storage - SSD 200 GB, network - up to 10 Gbps, Ubuntu [20.04.2.0](https://releases.ubuntu.com/20.04/)
- `Data Aggregator` : vCPU - 2, RAM - 4 GB. 
    - Aggregator reads data from Node and writes to Postgres. Only single aggregator should perform writing at a time
- Postgres: vCPU 2, RAM - 30 GB, storage - 500 GB
    - It is recommended to run database on dedicated host
    - It is recommended to have separated replicas for aggregator and snapshot polling client (i.e. for writes and reads respectively). One write replica and necessary amount of read replicas
- Snapshot client: depends on the way it will be integrated. TS database query layer itself is very simple and performant - probably no more than 1 vCPU and 1 Gb of RAM under high load. It is stateless, so it is possible to run more than one if required.

For development purposes the whole stack can be run on the single machine with decent CPU under 40-60 Gb of space and 16 Gb RAM.

`docker compose` setup to run all required parts was added to the repo together with instructions.

Further considerations:
- Aggregator reads a lot of data from the node that takes space, but not required for snapshot polling. I suppose, it possible to save a lot of space by making own aggregator, but this task could be pretty time consuming

**Comment by mikekeke** [comment]
Resolved by #9
